In [1]:
# Numpy: Provides fast mathematical functions
# Provides fast mathematical functions
# Efficiently implemented multi-dimensional arrays

import numpy as np
a = np.array([1,2,3])

In [2]:
type(a)

numpy.ndarray

In [3]:
x = np.zeros( (3,4) )
x 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones( (3,4), dtype=np.int16 )

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [5]:
np.full( (3,4), 0.11 )

array([[0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11]])

In [7]:
# np.arange - Creating sequence of Numbers

np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [8]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [9]:
# np.random.rand - Creating an array with random numbers
np.random.rand(2,3)

array([[0.97257051, 0.20958556, 0.90001464],
       [0.84114179, 0.25084387, 0.25957099]])

In [12]:
#np.empty - Creating an empty array
a=np.empty((2,3))


In [13]:
a.shape

(2, 3)

In [15]:
#elements of shape.

a.size

6

In [16]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [17]:
b = a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [18]:
# Indexing of an array
a = np.array([1, 5, 3, 19, 13, 7, 3])

a[3]

19

In [19]:
a[2:5] #range

array([ 3, 19, 13])

In [20]:
a[::-1] #Go reverse

array([ 3,  7, 13, 19,  3,  5,  1])

In [21]:
# Normal arraya and Numpy array
a[::-1] #Go reverse
a[::-1] #Go reverse
a


array([ 1,  5,  3, 19, 13,  7,  3])

In [22]:
b = [1, 2, 5, 7, 8]
b[1:3] = -1

TypeError: can only assign an iterable

In [24]:
another_slice = a[2:6].copy()
another_slice

array([ 3, 19, 13,  7])

In [26]:
# Multi-dimensional arrays can be accessed as
# >>> b[1, 2] # row 1, col 2
# >>> b[1, :] # row 1, all columns
# >>> b[:, 1] # all rows, column 1

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
rows_on = np.array([ True, False, False])

In [30]:
a[rows_on , : ]

array([[0, 1, 2, 3]])

In [36]:
# Linear Algebra with NumPy
#A vector can be represented by an array of numbers called scalars.

X = np.random.random((100, 100))
Y = np.random.random((100, 100))

def multiply_loops(A, B):
    C = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[1]):
        for j in range(B.shape[0]):
            C[i, j] = A[i, j] * B[j, i]
    return C

def multiply_Vector(A, B):
    return A @ B

%timeit multiply_loops(X, Y)

%timeit multiply_Vector(X, Y)


4.3 ms ± 98.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
38.2 µs ± 9.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [37]:
a = np.array( [20, 30, 40, 50] )
b = np.arange( 4 )

b

array([0, 1, 2, 3])

In [38]:
c = a + b
c

array([20, 31, 42, 53])

In [39]:
c = a - b
c

array([20, 29, 38, 47])

In [40]:
a*b

array([  0,  30,  80, 150])

In [42]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [50]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
print(b)

c = a / b
print(c)

c = a // b
print(c)

c = a % b
print(c)

# Exponent
c = a ** b
print(c)

[1 2 3 4]
[20.         15.         13.33333333 12.5       ]
[20 15 13 12]
[0 0 1 2]
[     20     900   64000 6250000]


In [51]:
#Conditional operators are also applied element-wise
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

In [53]:
# min - returns the minimum element in the ndarray
# max - returns the maximum element in the ndarray
# sum - returns the sum of the elements in the ndarray
# prod - returns the product of the elements in the ndarray
# std - returns the standard deviation of the elements in the
# ndarray.
# var - returns the variance of the elements in the ndarray.

a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print("mean =", a.mean())

mean = 6.766666666666667


In [55]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [56]:
# Transpose of a Matrics
c.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])